import type { UpgradeConfig } from './combat.upgrades'

export type UpgradeModifierKey = keyof UpgradeConfig['modifiers']

export const UPGRADE_MODIFIER_KEYS = [
  'hpMult',
  'attackMult',
  'speedMult',
  'rangeAdd',
  'cooldownMult',
  'addFlying',
  'addAoE',
  'defenseAdd',
  'grantShield',
  'stealthWhileMoving',
  'onDeathSpawn',
  'periodicSpawn',
  'disableEnemyTech',
  'leaveAoePuddle',
  'damageReductionWhileMoving',
  'burrowWhileMoving',
  'onDeathPuddle',
  'multishot',
  'antiAirDamageMult',
  'grantAntiAir',
  'grantShieldFlat',
  'replicateOnKill',
  'resurrectOnce',
  'stealthUntilAttack',
  'executeThreshold',
  'lifestealMult',
  'groundDamageMult',
  'shieldDamageMult',
  'armorPierceRatio',
  'summonCounterDamageMult',
  'accuracyPenaltyResist',
  'grantRevealAura',
  'periodicAbilities',
  'triggerEffects',
  'transformMode',
  'controlBeam',
  'fieldEffect',
  'formationModifiers',
  'statGrowth',
  'attackCharge',
  'reassembly',
  'targetPriorityProfile',
  'conditionalAttackMode',
  'sweepAttack',
] as const satisfies readonly UpgradeModifierKey[]

export const RUNTIME_HANDLED_UPGRADE_MODIFIERS = [
  'hpMult',
  'attackMult',
  'speedMult',
  'rangeAdd',
  'cooldownMult',
  'addFlying',
  'addAoE',
  'defenseAdd',
  'grantShield',
  'periodicSpawn',
  'disableEnemyTech',
  'leaveAoePuddle',
  'damageReductionWhileMoving',
  'burrowWhileMoving',
  'onDeathPuddle',
  'multishot',
  'antiAirDamageMult',
  'grantAntiAir',
  'grantShieldFlat',
  'replicateOnKill',
  'resurrectOnce',
  'stealthUntilAttack',
  'executeThreshold',
  'lifestealMult',
  'groundDamageMult',
  'shieldDamageMult',
  'armorPierceRatio',
  'summonCounterDamageMult',
  'accuracyPenaltyResist',
  'grantRevealAura',
  'periodicAbilities',
  'triggerEffects',
  'transformMode',
  'controlBeam',
  'fieldEffect',
  'formationModifiers',
  'statGrowth',
  'attackCharge',
  'reassembly',
  'targetPriorityProfile',
  'conditionalAttackMode',
  'sweepAttack',
] as const satisfies readonly UpgradeModifierKey[]

export const DEFERRED_UPGRADE_MODIFIERS = [
  'stealthWhileMoving',
  'onDeathSpawn',
] as const satisfies readonly UpgradeModifierKey[]

type ListedModifierKey = typeof UPGRADE_MODIFIER_KEYS[number]
type MissingModifierKey = Exclude<UpgradeModifierKey, ListedModifierKey>
type ExtraModifierKey = Exclude<ListedModifierKey, UpgradeModifierKey>
export const UPGRADE_MODIFIER_KEY_COVERAGE: MissingModifierKey extends never ? ExtraModifierKey extends never ? true : never : never = true
