import type { UnitDefinition } from '@mars2050/combat-core/contracts'

export const FANTASY_DEFINITIONS: Record<string, UnitDefinition> = {
  orc_warrior: {
    id: 'orc_warrior',
    name: 'Orc Warrior',
    baseStats: {
      hp: 120,
      attack: 25,
      defense: 6,
      speed: 6,
      range: 1,
      attackType: 'single',
      actionCooldownMax: 10,
      turnSpeed: 5,
      size: 'M',
      combatTags: ['melee', 'warrior'],
    },
    squadSize: 3,
    squadSpacing: 25,
    formation: 'line',
  },
  elven_archer: {
    id: 'elven_archer',
    name: 'Elven Archer',
    baseStats: {
      hp: 60,
      attack: 20,
      defense: 2,
      speed: 5,
      range: 5,
      attackType: 'single',
      actionCooldownMax: 12,
      turnSpeed: 8,
      size: 'S',
      combatTags: ['ranged', 'archer'],
    },
    squadSize: 4,
    squadSpacing: 30,
    formation: 'wedge',
  },
  goblin_shaman: {
    id: 'goblin_shaman',
    name: 'Goblin Shaman',
    baseStats: {
      hp: 80,
      attack: 0,
      defense: 3,
      speed: 4,
      range: 4,
      attackType: 'spawn',
      spawnType: 'fire_elemental',
      spawnCap: 2,
      actionCooldownMax: 20,
      turnSpeed: 6,
      size: 'S',
      combatTags: ['magic', 'summoner'],
    },
    squadSize: 1,
    squadSpacing: 20,
    formation: 'grid',
  },
  fire_elemental: {
    id: 'fire_elemental',
    name: 'Fire Elemental (Summoned)',
    baseStats: {
      hp: 50,
      attack: 30,
      defense: 1,
      speed: 8,
      range: 1,
      attackType: 'aoe',
      actionCooldownMax: 8,
      turnSpeed: 10,
      size: 'S',
      combatTags: ['elemental', 'summoned'],
    },
    squadSize: 1,
    squadSpacing: 10,
    formation: 'grid',
  },
}
